from wordpress:latest
MAINTAINER http://bestjimmy.com <bestjimmy@foxmail.com>
RUN touch uploads.ini && \
echo file_uploads = On >uploads.ini && \
echo memory_limit = 64M >uploads.ini && \
echo upload_max_filesize = 64M >uploads.ini && \
echo post_max_size = 64M >uploads.ini && \
echo max_execution_time = 600 >uploads.ini && \
mv uploads.ini /usr/local/etc/php/conf.d/
